# -*- coding: utf-8 -*-
"""Project4-CV-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1XREeX_hqI76gzO0b2s_hS3bB8XikOg
"""

# Install Tesseract OCR engine and required Python packages
!apt-get update -qq && apt-get install -y tesseract-ocr > /dev/null
!pip install pytesseract pillow matplotlib opencv-python-headless > /dev/null

import cv2
import pytesseract
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

print("✓ Environment successfully configured!")

print("Upload a sample image containing text (JPG or PNG):")
uploaded = files.upload()

# Get the uploaded image filename
image_path = list(uploaded.keys())[0]

# Load image using OpenCV
image_bgr = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

print(f"✓ Successfully loaded: {image_path}")

# ==============================================================================
# DECODELABS PROJECT 4: OPTICAL CHARACTER RECOGNITION (OCR) PIPELINE
# ==============================================================================

# ------------------------------------------------------------------------------
# STEP 1: Systematic Image Pre-Processing Pipeline
# ------------------------------------------------------------------------------
# 1. Grayscale Conversion (Reduces 3D RGB matrix to 1D intensity)
gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)

# 2. Gaussian Blur (Smooths micro-imperfections & noise)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# 3. Adaptive / Otsu's Thresholding (Forces binary decision: Pure Black & White)
_, thresholded = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# ------------------------------------------------------------------------------
# STEP 2: Model Execution & Accuracy Benchmarking (Gatekeeper Rule >= 80%)
# ------------------------------------------------------------------------------
custom_config = r'--psm 6'

# Extract OCR results with bounding boxes & confidence scores
data = pytesseract.image_to_data(thresholded, config=custom_config, output_type=pytesseract.Output.DICT)

annotated_image = image_rgb.copy()
detected_words = []
confidences = []

num_boxes = len(data['text'])
for i in range(num_boxes):
    try:
        confidence = int(data['conf'][i])
    except (ValueError, TypeError):
        continue

    text = data['text'][i].strip()

    # Apply the DecodeLabs Gatekeeper Rule: Confidence >= 80%
    if confidence >= 80 and len(text) > 0:
        (x, y, w, h) = (data['left'][i], data['top'][i], data['width'][i], data['height'][i])

        # Draw bounding box (Green) around valid text
        cv2.rectangle(annotated_image, (x, y), (x + w, y + h), (0, 255, 0), 2)

        detected_words.append(text)
        confidences.append(confidence)

# ------------------------------------------------------------------------------
# STEP 3: Visual Confirmation Output
# ------------------------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

axes[0].imshow(image_rgb)
axes[0].set_title("1. Original Visual Input")
axes[0].axis('off')

axes[1].imshow(thresholded, cmap='gray')
axes[1].set_title("2. Pre-Processed (Otsu Threshold)")
axes[1].axis('off')

axes[2].imshow(annotated_image)
axes[2].set_title("3. Bounding Boxes (Conf >= 80%)")
axes[2].axis('off')

plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
# STEP 4: Output Verification Report
# ------------------------------------------------------------------------------
print("\n" + "="*50)
print("              MILESTONE VALIDATION REPORT            ")
print("="*50)
print(f"Extracted Text String : {' '.join(detected_words)}")
if confidences:
    avg_conf = sum(confidences) / len(confidences)
    print(f"Average Confidence   : {avg_conf:.2f}%")
    print(f"Gatekeeper Rule      : PASSED (>= 80% standard met)")
else:
    print("Gatekeeper Rule      : NO TEXT PASSED THE 80% THRESHOLD")
print("="*50)

